### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by el-j** [abetusk/www.meowcad.com#28]
Hej there, i stumbled upon meowcad and really like the page and the style.
sadly i got an internal server error when i try to register. 
![image](https://user-images.githubusercontent.com/2795534/47722745-66ce6a00-dc53-11e8-9418-1dd718c783e0.png)

is this project still active? greetings + thanks

**Comment by abetusk** [comment]
Thank you for the report. The server is a bit flaky and occasionally has services that need restarting. The proper solution is to have checks in place that make sure the system is working nominally and restart services as necessary but in the meantime, I restart them myself.

I've just tried to register successfully so registration as well as other services that went down should be operational now.

**Comment by el-j** [comment]
i was able to register now.
thank you.
