### ISSUE TITLE
Expired certificate on website

### ISSUE THREAD

**Issue by mostlybob** [abetusk/www.meowcad.com#29]
I don't know if this is the appropriate place for this, but I get warnings from both Firefox and Brave on Windows 64 that the site's certificate expired on 2019-12-11. Firefox gave me this article to share, but I don't know what, if any, use you'll have for it:

https://support.mozilla.org/en-US/kb/troubleshoot-time-errors-secure-websites

**Comment by abetusk** [comment]
Thank you for the report. I have updated the certificate and things should be working now.

In the future I need to automate this more.
